In [36]:
import pandas as pd
df = pd.read_csv(r"weather.csv")
print(df)
type(df)

          day  temperature  windspeed  humidity  event
0  01-01-2017           32          6        20   Rain
1  01-02-2017           35          7        30  Sunny
2  01-03-2017           28          2        45   Snow
3  01-04-2017           24          7        40   Snow
4  01-05-2017           32          4        35   Rain
5  01-06-2017           31          2        20  Sunny

pandas.core.frame.DataFrame

In [4]:
#creating dataframe
weather_data = [['1/1/2017',32,6,20,'Rain'],
                ['1/2/2017',35,7,30,'Sunny'],
                ['1/3/2017',28,2,25,'Snow'],
                ['1/4/2017',24,7,45,'Snow'],
                ['1/5/2017',32,4,35,'Rain'],
                ['1/6/2017',31,2,20,'Sunny']]
df1= pd.DataFrame(weather_data,columns=['day','temperature','windspped','humidity','event'])
df1

        day  temperature  windspped  humidity  event
0  1/1/2017           32          6        20   Rain
1  1/2/2017           35          7        30  Sunny
2  1/3/2017           28          2        25   Snow
3  1/4/2017           24          7        45   Snow
4  1/5/2017           32          4        35   Rain
5  1/6/2017           31          2        20  Sunny

## WORKING ON ROWS AND COLUMNS

In [5]:
print(df.shape) #to get the shape of the table/database

(6, 5)

In [6]:
#to print different columns there in the dataset
print(df.columns)

Index(['day ', 'temperature', 'windspeed', 'humidity', 'event'], dtype='object')

In [7]:
print(df.head)#to display first 5 columns
print(df.head(3))#to display first 3 columns

<bound method NDFrame.head of          day   temperature  windspeed  humidity  event
0  01-01-2017           32          6        20   Rain
1  01-02-2017           35          7        30  Sunny
2  01-03-2017           28          2        45   Snow
3  01-04-2017           24          7        40   Snow
4  01-05-2017           32          4        35   Rain
5  01-06-2017           31          2        20  Sunny>
         day   temperature  windspeed  humidity  event
0  01-01-2017           32          6        20   Rain
1  01-02-2017           35          7        30  Sunny
2  01-03-2017           28          2        45   Snow

In [8]:
print(df.tail)#to display last 5 columns
print(df.tail(3))#to display last 3 columns

<bound method NDFrame.tail of          day   temperature  windspeed  humidity  event
0  01-01-2017           32          6        20   Rain
1  01-02-2017           35          7        30  Sunny
2  01-03-2017           28          2        45   Snow
3  01-04-2017           24          7        40   Snow
4  01-05-2017           32          4        35   Rain
5  01-06-2017           31          2        20  Sunny>
         day   temperature  windspeed  humidity  event
3  01-04-2017           24          7        40   Snow
4  01-05-2017           32          4        35   Rain
5  01-06-2017           31          2        20  Sunny

In [18]:
print(df.sample(2))#to display random 2 samples

         day   temperature  windspeed  humidity  event
1  01-02-2017           35          7        30  Sunny
4  01-05-2017           32          4        35   Rain

In [25]:
#to print the data of a single column
df1.day

0    1/1/2017
1    1/2/2017
2    1/3/2017
3    1/4/2017
4    1/5/2017
5    1/6/2017
Name: day, dtype: object

In [35]:
df['day']

KeyError: 'day'

In [28]:
df1[['day','event']]

        day  event
0  1/1/2017   Rain
1  1/2/2017  Sunny
2  1/3/2017   Snow
3  1/4/2017   Snow
4  1/5/2017   Rain
5  1/6/2017  Sunny

In [34]:
#to print temperature column value
df.temperature.describe()

count     6.000000
mean     30.333333
std       3.829708
min      24.000000
25%      28.750000
50%      31.500000
75%      32.000000
max      35.000000
Name: temperature, dtype: float64

In [37]:
df.info() #to get how many null values are there

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          6 non-null      object
 1   temperature  6 non-null      int64
 2   windspeed    6 non-null      int64
 3   humidity     6 non-null      int64
 4   event        6 non-null      object
dtypes: int64(3), object(2)
memory usage: 368.0+ bytes

In [38]:
df.iloc[2,4] #position based indexing

'Snow'

In [39]:
df.loc[2,'event'] #lable based indexing

'Snow'

In [41]:
df.loc[4,'temperature']

32

## OPERATIONS

In [45]:
#print the maximum temperature
print(max(df.temperature))

35

In [46]:
df['temperature'].max() #another way to print max

35

In [48]:
df['temperature'].min() #to print the minimum

24

In [49]:
df['temperature'].std() #to print the std

3.8297084310253524

In [53]:
#describe the columns temperature
df.temperature.describe()

count     6.000000
mean     30.333333
std       3.829708
min      24.000000
25%      28.750000
50%      31.500000
75%      32.000000
max      35.000000
Name: temperature, dtype: float64

In [52]:
df.temperature == df.temperature.max()

0    False
1     True
2    False
3    False
4    False
5    False
Name: temperature, dtype: bool

In [54]:
df.temperature == df.temperature.min()

0    False
1    False
2    False
3     True
4    False
5    False
Name: temperature, dtype: bool

In [56]:
#select rows which has maximum temperature
df[df.temperature == df.temperature.max()]

          day  temperature  windspeed  humidity  event
1  01-02-2017           35          7        30  Sunny

In [57]:
#select rows which has minimum temperature
df[df.temperature == df.temperature.min()]

          day  temperature  windspeed  humidity event
3  01-04-2017           24          7        40  Snow

In [58]:
#select only day column which has maximum temperature
df.day[df.temperature == df.temperature.max()]

1    01-02-2017
Name: day, dtype: object

In [59]:
df.index #to show the staring and ending position stepwise

RangeIndex(start=0, stop=6, step=1)

In [60]:
df.set_index('day') #it will not modify the original dataframe

            temperature  windspeed  humidity  event
day
01-01-2017           32          6        20   Rain
01-02-2017           35          7        30  Sunny
01-03-2017           28          2        45   Snow
01-04-2017           24          7        40   Snow
01-05-2017           32          4        35   Rain
01-06-2017           31          2        20  Sunny

In [61]:
df.set_index('day',inplace=True) #modifies the original datafram
df

            temperature  windspeed  humidity  event
day
01-01-2017           32          6        20   Rain
01-02-2017           35          7        30  Sunny
01-03-2017           28          2        45   Snow
01-04-2017           24          7        40   Snow
01-05-2017           32          4        35   Rain
01-06-2017           31          2        20  Sunny

In [62]:
df.reset_index(inplace=True) #reset to the original dataframe again
df

          day  temperature  windspeed  humidity  event
0  01-01-2017           32          6        20   Rain
1  01-02-2017           35          7        30  Sunny
2  01-03-2017           28          2        45   Snow
3  01-04-2017           24          7        40   Snow
4  01-05-2017           32          4        35   Rain
5  01-06-2017           31          2        20  Sunny

In [65]:
#sort particular values under a particular name
df.sort_values(['windspeed'])

          day  temperature  windspeed  humidity  event
2  01-03-2017           28          2        45   Snow
5  01-06-2017           31          2        20  Sunny
4  01-05-2017           32          4        35   Rain
0  01-01-2017           32          6        20   Rain
1  01-02-2017           35          7        30  Sunny
3  01-04-2017           24          7        40   Snow