# Data Preprocessing tools

## Importing the libraries

In [8]:
import numpy as np
import matplotlib.pyplot as pit
import pandas as pd

In [11]:
dataset = pd.read_csv(r"sample.csv")
print(dataset)
type(dataset)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

pandas.core.frame.DataFrame

In [14]:
#numpy
X_raw = dataset.iloc[:, :-1].values
y_raw = dataset.iloc[:, -1].values
print('xraw')
print(X_raw)
print('yraw')
print(y_raw)

xraw
[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
yraw
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']

In [15]:
#pandas
dfX_raw = dataset.iloc[:, :-1]
seriesy_rawdfX = dataset.iloc[:, -1]
print('dfxraw')
print(dfX_raw)
print('seriesy_rawdfX')
print(seriesy_rawdfX)

dfxraw
   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0
seriesy_rawdfX
0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

In [16]:
#copy the data to another variable
dfX = dfX_raw.copy()
seriesy = seriesy_rawdfX.copy()
X = X_raw.copy()
y = y_raw.copy()

In [17]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]

In [18]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']

In [20]:
print(type(dfX))
print(type(X))

<class 'pandas.core.frame.DataFrame'>
<class 'numpy.ndarray'>

In [21]:
print(type(seriesy))
print(type(y))

<class 'pandas.core.series.Series'>
<class 'numpy.ndarray'>

## Take care of missing data

In [22]:
print(dfX.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  10 non-null     object
 1   Age      9 non-null      float64
 2   Salary   9 non-null      float64
dtypes: float64(2), object(1)
memory usage: 368.0+ bytes
None

In [24]:
print(X.info())  #info will not work in the numpy array

AttributeError: 'numpy.ndarray' object has no attribute 'info'

In [27]:
#change the numpy array to dataframe
X = pd.DataFrame(X)
X.info()       #now X will act as a dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       10 non-null     object
 1   1       9 non-null      object
 2   2       9 non-null      object
dtypes: object(3)
memory usage: 368.0+ bytes

In [30]:
#Then change it to numpy
X = X.values
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [32]:
print(dfX.isnull().sum())

Country    0
Age        1
Salary     1
dtype: int64

In [34]:
print(X.isnull.sum())  #no isnull in numpy

AttributeError: 'numpy.ndarray' object has no attribute 'isnull'

In [35]:
dfX_raw

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [37]:
dfX = dfX.fillna(0)
dfX

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      0.0
5   France  35.0  58000.0
6    Spain   0.0  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [38]:
dfX = dfX.replace(0, np.nan) #call nan through the n object
dfX

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [40]:
index_no = dfX.columns.get_loc('Age')  #displays the index of age column
index_no

1

In [41]:
dfX.iloc[:, 1] = dfX.iloc[:, 1].fillna(5)
dfX

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   5.0  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [42]:
#getting the old data
dfX = dfX_raw.copy()
dfX

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

# Missing value imputation in dataframe

## Replace with mean values

In [43]:
dfX_raw

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [44]:
#dataframe
#SimpleImputer is a class that is used to handle the missing values with simple strategies
#sklearn is the library and impute is the module
#fit is used in calculation
#transform-places where you specify there the calculated value is transfered
dfX = dfX_raw.copy()
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')

#imputer.fit(dfX.iloc[:, 1:3])
#dfX.iloc[:, 1:3] = imputer.transform(dfX.iloc[:, 1:3]).transform(dfX.iloc[:, 1:3])

dfX.iloc[:, 1:3] = imputer.fit_transform(dfX.iloc[:,1:3])
dfX

   Country        Age        Salary
0   France  44.000000  72000.000000
1    Spain  27.000000  48000.000000
2  Germany  30.000000  54000.000000
3    Spain  38.000000  61000.000000
4  Germany  40.000000  63777.777778
5   France  35.000000  58000.000000
6    Spain  38.777778  52000.000000
7   France  48.000000  79000.000000
8  Germany  50.000000  83000.000000
9   France  37.000000  67000.000000

In [45]:
#getting the original(old) data
dfX = dfX_raw.copy()
dfX

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

## Replace the constant values

In [49]:
#datafram
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'constant', fill_value=5)
imputer.fit(dfX.iloc[:, 1:3])
dfX.iloc[:, 1:3] = imputer.fit(dfX.iloc[:, 1:3]).transform(dfX.iloc[:, 1:3])
dfX

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      5.0
5   France  35.0  58000.0
6    Spain   5.0  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [50]:
#help(SimpleImputer)
SimpleImputer?

X_raw

In [53]:
#SimpleImputer in the numpy
X=X_raw.copy()
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]